### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by perigoso** [blackmagic-debug/bmputil#5]
source currently does not provide any licensing information

**Comment by dragonmux** [comment]
Ah, yes.. @Qyriad what license did you intend to release this under? A quick check of some of the files does indeed show you never put a license notice in any of them

**Comment by dragonmux** [comment]
No worries, we'll take that as permission to apply those licenses then and update the repo accordingly. Just to check, which BSD would you like us to use here? 3-clause or 2-clause (if another, please specify)

**Comment by Qyriad** [comment]
Ah wait sorry, it's MIT and *Apache 2.0* that's the standard, so let's go with that.
